### ISSUE TITLE
Je suis une merde en java script

### ISSUE THREAD

**Issue by I4MTRUE** [I4MTRUE/Random-Movie#1]
Ouais voila c'est tout c'etait juste pour dire que j'étais une merde en js et du coup que je suis lent a mort ... Donc si mon code est très inspiré ou est absolument déguelasse baaah va bien te mettre parce que j'apprend ....

**Comment by ghost** [comment]
such issue, try alt+F4

**Comment by I4MTRUE** [comment]
Thx m8
